In [1]:
import numpy as np
import scipy.stats as stats
np.random.seed(2019)

In [19]:
def simulate_days_ttests_with_samples(days_pairs, one_day, two_days,
                                      three_days, four_days, five_days,
                                      seed, sample_size=30):
    """Takes random samples from each of the days per week dataframes. """

    np.random.seed(seed)

    one_sample = np.random.choice(one_day, size=sample_size)
    two_sample = np.random.choice(two_days, size=sample_size)
    three_sample = np.random.choice(three_days, size=sample_size)
    four_sample = np.random.choice(four_days, size=sample_size)
    five_sample = np.random.choice(five_days, size=sample_size)

    for days1, days2 in days_pairs:
        if days1 == 1:
            first = one_sample
        elif days1 == 2:
            first = two_sample
        elif days1 == 3:
            first = three_sample
        else:
            first = four_sample
        if days2 == 2:
            second = two_sample
        elif days2 == 3:
            second = three_sample
        elif days2 == 4:
            second = four_sample
        else:
            second = five_sample
        print(days1, days2)
        print(stats.ttest_ind(first, second))

In [9]:
one_day = [1, 2, 3, 4, 5]
two_days = [6, 7, 8, 9, 10]
three_days = [11, 12, 13, 14, 15]
four_days = [16, 17, 18, 19, 20]
five_days = [21, 22, 23, 24, 25]

In [10]:
days_pairs = []
days = [1, 2, 3, 4, 5]

for days1 in range(4):
    for days2  in range(days1+1,5):
        days_pairs.append((days[days1], days[days2]))
        
print(days_pairs)

[(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]


In [20]:
simulate_days_ttests_with_samples(days_pairs, one_day, two_days, three_days, 
                                  four_days, five_days, sample_size=3, seed=2019)

1 2
Ttest_indResult(statistic=-4.749999999999999, pvalue=0.008970902498598023)
[1 3 1]
1 3
Ttest_indResult(statistic=-14.0, pvalue=0.00015101140222180054)
[1 3 1]
1 4
Ttest_indResult(statistic=-12.126781251816645, pvalue=0.00026529751656953444)
[1 3 1]
1 5
Ttest_indResult(statistic=-15.999999999999998, pvalue=8.921654238106093e-05)
[1 3 1]
2 3
Ttest_indResult(statistic=-2.598076211353316, pvalue=0.06016984650357827)
[1 3 1]
2 4
Ttest_indResult(statistic=-6.199999999999999, pvalue=0.0034417772554457505)
[1 3 1]
2 5
Ttest_indResult(statistic=-9.185586535436919, pvalue=0.0007801267925694845)
[1 3 1]
3 4
Ttest_indResult(statistic=-6.1017021584775195, pvalue=0.003650259898513397)
[1 3 1]
3 5
Ttest_indResult(statistic=-10.392304845413264, pvalue=0.00048412775835632527)
[1 3 1]
4 5
Ttest_indResult(statistic=-2.8000000000000007, pvalue=0.04881155054888408)
[1 3 1]


In [21]:
simulate_days_ttests_with_samples(days_pairs, one_day, two_days, three_days, four_days, five_days, sample_size=3, seed=10)

1 2
Ttest_indResult(statistic=-4.024922359499621, pvalue=0.015799848495268172)
[2 5 1]
1 3
Ttest_indResult(statistic=-7.216053531635459, pvalue=0.0019556862701064553)
[2 5 1]
1 4
Ttest_indResult(statistic=-10.75, pvalue=0.000424492291912209)
[2 5 1]
1 5
Ttest_indResult(statistic=-13.82453062707098, pvalue=0.00015869025608715285)
[2 5 1]
2 3
Ttest_indResult(statistic=-3.181980515339464, pvalue=0.033471744961631446)
[2 5 1]
2 4
Ttest_indResult(statistic=-7.905694150420948, pvalue=0.0013849379404235027)
[2 5 1]
2 5
Ttest_indResult(statistic=-11.758942438532781, pvalue=0.0002992430231973713)
[2 5 1]
3 4
Ttest_indResult(statistic=-8.000000000000002, pvalue=0.0013238969092171666)
[2 5 1]
3 5
Ttest_indResult(statistic=-13.416407864998742, pvalue=0.00017852131834470458)
[2 5 1]
4 5
Ttest_indResult(statistic=-5.291502622129183, pvalue=0.00612225663817181)
[2 5 1]
